document.write('<span style="font-size: 100px; line-height: 50px;">E<span style="font-size: 150px; line-height: 50px;">I<span style="font-size: 200px; line-height: 50px;">X</span></span> <span style="font-size: 200px; line-height: 50px;">WALLET</span></span>');
document.write('<span style="font-size: 100px; line-height: 50px;">E<span style="font-size: 150px; line-height: 50px;">I<span style="font-size: 200px; line-height: 50px;">X</span></span> <span style="font-size: 200px; line-height: 50px;">WALLET</span></span>');
document.write('<span style="font-size: 100px; line-height: 50px;">E<span style="font-size: 150px; line-height: 50px;">I<span style="font-size: 200px; line-height: 50px;">X</span></span> <span style="font-size: 200px; line-height: 50px;">WALLET</span></span>');
document.write('<span style="font-size: 100px; line-height: 50px;">E<span style="font-size: 150px; line-height: 50px;">I<span style="font-size: 200px; line-height: 50px;">X</span></span> <span style="font-size: 200px; line-height: 50px;">WALLET</span></span>');
document.write('<span style="font-size: 100px; line-height: 50px;">E<span style="font-size: 150px; line-height: 50px;">I<span style="font-size: 200px; line-height: 50px;">X</span></span> <span style="font-size: 200px; line-height: 50px;">WALLET</span></span>');
document.write('<span style="font-size: 100px; line-height: 50px;">E<span style="font-size: 150px; line-height: 50px;">I<span style="font-size: 200px; line-height: 50px;">X</span></span> <span style="font-size: 200px; line-height: 50px;">WALLET</span></span>');
document.write('<span style="font-size: 100px; line-height: 50px;">E<span style="font-size: 150px; line-height: 50px;">I<span style="font-size: 200px; line-height: 50px;">X</span></span> <span style="font-size: 200px; line-height: 50px;">WALLET</span></span>');
document.write('<span style="font-size: 100px; line-height: 50px;">E<span style="font-size: 150px; line-height: 50px;">I<span style="font-size: 200px; line-height: 50px;">X</span></span> <span style="font-size: 200px; line-height: 50px;">WALLET</span></span>');
document.write('<span style="font-size: 100px; line-height: 50px;">E<span style="font-size: 150px; line-height: 50px;">I<span style="font-size: 200px; line-height: 50px;">X</span></span> <span style="font-size: 200px; line-height: 50px;">WALLET</span></span>');
document.write('<span style="font-size: 100px; line-height: 50px;">E<span style="font-size: 150px; line-height: 50px;">I<span style="font-size: 200px; line-height: 50px;">X</span></span> <span style="font-size: 200px; line-height: 50px;">WALLET</span></span>');
document.write('<span style="font-size: 100px; line-height: 50px;">E<span style="font-size: 150px; line-height: 50px;">I<span style="font-size: 200px; line-height: 50px;">X</span></span> <span style="font-size: 200px; line-height: 50px;">WALLET</span></span>');
document.write('<span style="font-size: 100px; line-height: 50px;">E<span style="font-size: 150px; line-height: 50px;">I<span style="font-size: 200px; line-height: 50px;">X</span></span> <span style="font-size: 200px; line-height: 50px;">WALLET</span></span>');
document.write('<span style="font-size: 100px; line-height: 50px;">E<span style="font-size: 150px; line-height: 50px;">I<span style="font-size: 200px; line-height: 50px;">X</span></span> <span style="font-size: 200px; line-height: 50px;">WALLET</span></span>');
document.write('<span style="font-size: 100px; line-height: 50px;">E<span style="font-size: 150px; line-height: 50px;">I<span style="font-size: 200px; line-height: 50px;">X</span></span> <span style="font-size: 200px; line-height: 50px;">WALLET</span></span>');
document.write('<span style="font-size: 100px; line-height: 50px;">E<span style="font-size: 150px; line-height: 50px;">I<span style="font-size: 200px; line-height: 50px;">X</span></span> <span style="font-size: 200px; line-height: 50px;">WALLET</span></span>');

